config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :roasts
  resources :items
  resources :stocks
  devise_for :users
  # get 'home/index'
  root 'home#index'
  get 'tasting' => 'home#tasting'
  get "brewing" => 'home#brewing'
  get "hario" => 'home#hario'
  get "stovetop" => 'home#stovetop'
  get "aeropress" => 'home#aeropress'
  get "french_press" => 'home#french_press'
  get "delter_press" => 'home#delter_press'
  get "chemex" => 'home#chemex'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @gbeans = Stock.all
    @roasts = Roast.includes(:comments).order("created_at DESC").limit(3)
    @items = Item.order("created_at DESC").limit(4)
  end

  def brewing
  end

  def hario
  end

  def stovetop
  end

  def aeropress
  end

  def french_press
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/home/_footer.html.erb
<footer class='footer'>
  <div class="footer__copyright">&copy; 2020 DSC</div>
  <div class="footer__signature">Made by Dan C</div>
</footer> 

app/views/home/_navbar.html.erb
<div class="grid-container">

<% if user_signed_in? %>
<nav class="navbar navbar-expand-lg navbar-dark" style="background: #2C3532;">
  <%= link_to "/", class: "navbar-brand" do %>
      <%= image_tag "coffee-seeds.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">

        <%= link_to "Home", root_path, class: "nav-link" %>

      </li>
      <li class="nav-item">
        <%= link_to "Batches", roasts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "GreenBeans", stocks_path, class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Resources
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "Notes", items_path, class: "dropdown-item" %>
          <%= link_to "Brewing Guides", brewing_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
            <%= link_to "Tasting Centre", tasting_path, class: "dropdown-item" %>
        </div>
      </li>
    </ul>
    <% if user_signed_in? %>
      <li class="nav-item dropdown">
        <% if current_user.avatar %>
          <%= image_tag "#{current_user.avatar}", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
          <%= image_tag "https://media1.tenor.com/images/ed2ef9bceac44da18c2eb0711df61106/tenor.gif", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Account", edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
    <% end %>
  </div>
</nav>
<% end %>

app/views/home/aeropress.html.erb
<div class="container">
  <div class="row">  
    <div class="col-md-6">  
      <div class="section-heading">
        <h1>Aeropress</h1>
      </div>
      <div class="section-body">
        <h2>(upside down method)</h2>
        <p>Boil water and measure out coffee. 16 grams coffee to 200 grams of water works well.</p>
        <p>Wet the paper filter</p>
        <p>With the Aeropress upside down and sitting on the scale, add the coffee grounds. Set the scale to 0</p>
        <p>Start your timer and then immediately start pouring. Pour quickly making sure that all the coffee grounds are wet. Pour to 200grams on the scale.</p>
        <p>Give the coffee a quick stir, replace the filter cap <strong>tightly</strong> with paper filter inside. Then wait until the timer reaches 1 minute and 30 seconds.</p>
        <p>Quickly flip the Aeropress over and ontop of glass. And gently but firmly press down on the plunger. If the cap is not on tightly, hot coffee liquid will spurt out.</p>
        <p>Once you hear the air hissing out, stopping pressing and serve.</p>
      </div>
    </div>
    <div class="col-md-6">
    <br/><br/><br/>
      <%= image_tag ("aeropress_7.webp"), class: "section-image" %>
    </div>
  </div>
</div>

app/views/home/brewing.html.erb
<div class="heading">
    <center><h1>Brewing Guides</h1></center>
</div>
<div class="container">
  
  <br/>
  <br/>
  <div class="methods">
    <div class="row">
      <div class="col-md-4">
      <%= link_to hario_path do %>  
        <div class="card">
          <%= image_tag ("hario-v60.jpg"), class: "card-img-top", style: "height: 15rem;" %>
          <div class="card-body">
            <h5 class="card-title">V60 Pour Over</h5>
            <p class="card-text">Brew Guide</p>
          </div>
        </div>
        <% end %>
      </div>

      <div class="col-md-4">
      <%= link_to stovetop_path do %>
        <div class="card">
          <%= image_tag ("Moka-Pot.jpg"), class: "card-img-top", style: "height: 15rem;" %>
          <div class="card-body">
            <h5 class="card-title">Stove Top</h5>
            <p class="card-text">Brew Guide</p>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-md-4">
      <%= link_to aeropress_path do %>
        <div class="card">
          <%= image_tag ("aeropress_7.webp"), class: "card-img-top", style: "height: 15rem;" %>
          <div class="card-body">
            <h5 class="card-title">Aeropress</h5>
            <p class="card-text">Brew Guide</p>
          </div>
        </div>
        <% end %>
      </div>
    </div>
<br>
      <div class="row">
      <div class="col-md-4">
      <%= link_to french_press_path do %>
        <div class="card">
          <%= image_tag ("french.png"), class: "card-img-top", style: "height: 15rem;" %>
          <div class="card-body">
            <h5 class="card-title">French Press</h5>
            <p class="card-text">Brew Guide</p>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-md-4">
      <%= link_to chemex_path do %>  
        <div class="card">
          <%= image_tag ("https://images.crateandbarrel.com/is/image/Crate/Chemex8CupCffeMkrWWdCollrSHF16/?$web_product_hero$&190411134920&wid=625&hei=625"), class: "card-img-top", style: "height: 15rem;" %>
          <div class="card-body">
            <h5 class="card-title">Chemex</h5>
            <p class="card-text">Brew Guide</p>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-md-4">
      <%= link_to delter_press_path do %>  
        <div class="card">
          <%= image_tag ("https://cdn.shopify.com/s/files/1/0229/4212/2061/articles/delter-coffee-press-delter-4_704x704_5ef3452e-8b77-4cd4-a84b-7585ad972359_1600x.jpg?v=1570144120"), class: "card-img-top", style: "height: 15rem;" %>
          <div class="card-body">
            <h5 class="card-title">Delter Press</h5>
            <p class="card-text">Brew Guide</p>
          </div>
        </div>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>


  

app/views/home/chemex.html.erb
<div class="container">
  <div class="row">  
    <div class="col-md-6">  
      <div class="section-heading">
        <h1>Chemex</h1>
      </div>
      <div class="section-body">
        <h5>Step 1</h5>
        <p>Note: The amount of coffee and water varies depending on the type of coffee you are brewing and your preferred strength. As a starting point, we recommend using 50 grams of coffee and 700 grams of water (about 25 ounces), and then adjust according to your taste.</p>
        
        </p>Weigh out the coffee and grind to a coarseness resembling sea salt</p>

        <h5>Step 2</h5>
        <p>Unfold your filter and place it in your Chemex, ensuring that the triple-fold portion is facing the pour spout and lays across without obstructing it.</p>

        <h5>Step 3</h5>
        <p>Fully saturate the filter and warm the vessel with hot water. Discard this water through the pour spout.</p>

        <h5>Step 4</h5>
        <p>Pour your ground coffee into the filter and give it a gentle shake. This will flatten the bed, allowing for a more-even pour.</p>

        <h5>Step 5</h5>
        <p>There will be four pours total, and this is the first.</p>
        <p>Starting at the bed’s center, gently pour twice the amount of water that you have coffee into your grounds (for example, 50 grams of water if you have 25 grams of coffee). Work your way gently outward, and avoid pouring down the sides of the filter. You’ll notice that adding this amount of water causes the coffee to expand, or “bloom.” Allow it to do so for 45–55 seconds. A solid bloom ensures even saturation.</p>

        <h5>Step 6</h5>

        <p>Pour water in a circular pattern starting in the center. Spiral out toward the edge of the slurry before spiraling back toward the middle. Avoid pouring on the filter. Allow the water to drip through the grounds until the slurry drops 1 inch from the bottom of the filter. You should use about 200 grams of water for this pour.</p>

        <h5>Step 7</h5>
        <p>Repeat the same pour pattern as in Step 6, adding water in 200-gram increments. Repeat once more, allowing the water to percolate through the grounds until the slurry drops 1 inch from the bottom of the filter before beginning the next pour.</p>

        <h5>Step 8</h5>
        <p>Allow the water to drip through the grounds entirely.</p>

        <h5>Step 9</h5>
        <p>The brew should have taken between 3.5–4.5 minutes. If the brew was too fast, consider using a finer grind or a slower pour rate next time. If the brew was too slow, consider using a coarser grind or a faster pour rate.</p>
      </div>
    </div>
    <div class="col-md-6">
      <br/><br/><br/>
      <%= image_tag ("https://images.crateandbarrel.com/is/image/Crate/Chemex8CupCffeMkrWWdCollrSHF16/?$web_product_hero$&190411134920&wid=625&hei=625"), class: "section-image" %>
      
      <div class="row">  
        <div class="col-md-12">
        <br>
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="5"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="6"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="7"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="https://bluebottlecoffee.com/assets/brew-guides/steps/shared-course-grinds-ba6a11b55b497a90c12bd97a0e65a7d98fd7eacd389cfedabe2fab9b91c844f3.jpg" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://bluebottlecoffee.com/assets/brew-guides/steps/chemex-step-2a-216bb950e89bef81871282a0c01cd5b6fc32bd0981e216fb3f8c11099095d1a4.jpg" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://bluebottlecoffee.com/assets/brew-guides/steps/chemex-step-2b-a462aee71e358c69e5e03091f53b576d270da9c4e2471baeb63021f091b66a86.jpg" class="d-block w-100" alt="...">  
          </div>
          <div class="carousel-item">
            <img src="https://bluebottlecoffee.com/assets/brew-guides/steps/chemex-step-3-8d7255b3061d0e57d7a950152de02e17545f11cfe20b8c1b8ad1ebcb3126d196.jpg" class="d-block w-100" alt="..."> 
          </div>
          <div class="carousel-item">
            <img src="https://bluebottlecoffee.com/assets/brew-guides/steps/chemex-step-4-d0bc86c70968ba18787f0ea8ab2b805d8b655d88bec63bb89a3134f2b87c9481.jpg" class="d-block w-100" alt="..."> 
          </div>
          <div class="carousel-item">
            <img src="https://bluebottlecoffee.com/assets/brew-guides/steps/chemex-step-5-204c25f26413376e44e6bc4ca8b1bf58848aaeb672706ccc8f17749f797e0690.jpg" class="d-block w-100" alt="..."> 
          </div>
          <div class="carousel-item">
            <img src="https://bluebottlecoffee.com/assets/brew-guides/steps/chemex-step-6-826d3d5ba7caca1850f3c4252783050fc26fef6e55af623ed41f651b1b8cc06f.jpg" class="d-block w-100" alt="..."> 
          </div>
          <div class="carousel-item">
            <img src="https://bluebottlecoffee.com/assets/brew-guides/steps/chemex-step-8-f4c8557c5610804416af3033b68cb3f6f9f4b899ae916d4176e8b49b6e10960a.jpg" class="d-block w-100" alt="..."> 
          </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/delter_press.html.erb
<div class="container">
  <div class="row">  
    <div class="col-md-6">  
      <div class="section-heading">
        <h1>Delter Press</h1>
      </div>
      <div class="section-body">
        
      </div>
    </div>
    <div class="col-md-6">
    <br/><br/><br/>
      <%= image_tag ("https://cdn.shopify.com/s/files/1/0229/4212/2061/articles/delter-coffee-press-delter-4_704x704_5ef3452e-8b77-4cd4-a84b-7585ad972359_1600x.jpg?v=1570144120"), class: "section-image" %>
    </div>
  </div>
</div>

app/views/home/french_press.html.erb
<div class="container">
  <div class="row">  
    <div class="col-md-6">  
      <div class="section-heading">
        <h1>French Press</h1>
      </div>
      <div class="section-body">
        <h5>Preparation</h5>
        <p>Boil fresh water in an electric or stove-top kettle. Set the temperature to 99ºC if possible.</p>
        <p>Seriously hot water is one of the most important elements of a great french press coffee, you want the water to be at a rolling boil before adding it immediately to the coffee.</p>
        <p>Measure out 19g of filter coffee and grind coarsely. The texture should be similar to flakes of rock salt. Add the ground coffee to your empty french press.</p>
        
        <h5>Brew</h5>
        <p>Quickly but carefully add 300g of boiling water to the french press.</p>
        <p>Stir the slurry gently so all grounds are completely saturated.</p>
        <p>Put the lid on top of the french press, but don’t plunge, and let it brew for 4 minutes.</p>
        
        <h5>Scoop and serve</h5>
        <p>After four minutes has passed, remove the lid and scoop the layer of brown foam and coffee grounds that are left on the surface of the french press.</p>
        <p>Replace the lid, plunge gently and pour immediately into cups or another vessel for serving. Do not serve direcly from the french press</p>
        
        <h5>Notes and cautions</h5>
        <p>If you cannot plunge the french press gently with two fingers, stop immediately. Some glass vessels can crack and break under high pressure. This is normally a sign that your grind is too fine and needs to be coarser.</p>
        <p>If you are after a stronger brew, try adding more coffee (say 22g instead of 19g) until you find a sweet spot that suits your tastes.</p>
        <p>For a more floral and ‘lighter’ brew, try shortening your brew time to 3:30 or 3:45.</p>
      </div>
    </div>
    <div class="col-md-6"> 
      <br/><br/><br/>
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="https://www.dukescoffee.com.au/assets/files/2014/03/Pouring-455x342.jpg" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://www.dukescoffee.com.au/assets/files/2014/03/Pressing-455x553.jpg" class="d-block w-100" alt="...">
          </div>
          <div class="carousel-item">
            <img src="https://www.dukescoffee.com.au/assets/files/2014/03/Serving-455x350.jpg" class="d-block w-100" alt="...">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="heading">
  <center><h1>RoastHub</h1></center>
</div>  

<main class="main">
<div class="container mt-3">Hello <%= current_user.email %></div>
  <div class="main-header">
      <div class="main-header_updates">
      <p>Recent Roasts:</p>
            <% @roasts.each do |roast| %>
                <%= link_to roast_path(roast) do%>
                <%= roast.date %>
                <%= roast.beans %><br>
                <% end %>
            <%end%>
      </div>
  </div>
  <div class="container"><p>Recent Notes</p></div>
    
  <div class="main-overview">
    <% @items.each do |item| %>
        <%= link_to item_path(item) do%>    
            <div class="overviewcard">
                
                <% if item.user.avatar %>
                            <%= image_tag "#{item.user.avatar}", class: "overview_avatar" %>
                        <% else %>
                            <%= image_tag "https://media1.tenor.com/images/ed2ef9bceac44da18c2eb0711df61106/tenor.gif", class: "overview_avatar red" %>
                        <% end %>
                        <div class="overviewcard_text red">
                    <div class="overviewcard_header red"><%= truncate(item.title, :length => 18) %></div>
                
                <div class="overviewcard_content red"><%= truncate(item.content, :length => 30) %></div>
                </div>
            </div>
        <% end %>
    <% end %>
  </div>
  <div class="container">
    <p>Currently in stock</p></div>
    <div class="main-cards">
        <table data-toggle="table" class="table table-striped table-bordered table-sm table-dark" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th class="th-sm">Country</th>  
                <th class="th-sm">Beans</th>
                <th class="th-sm">Quantity(kg)</th>
            </tr>
        </thead>
        <tbody>
        <% @gbeans.each do |gbean| %>
            <tr>
                <th scope="row"><%= gbean.country %></th>
                <td><%= gbean.bean %></td>
                <td class=""><%= gbean.amount %></td>
            </tr>
        <% end %>
        </tbody>
        </table>
    </div>
  </div>
</main>

app/views/home/roasting.html.erb
<center>
<div="heading"><h1>Roasting Resources</h1></div>
</center>

<% @items.each do |item| %>
    <br/><%= item.title %><br/>
    <%= item.link %><br/>
    <%= item.content %><br/>
    <%= link_to 'Open', item_path(item), class: "btn btn-primary" %>
<% end %>

app/views/home/tasting.html.erb
<div class="heading">
    <center><h1>Tasting Centre</h1></center>
</div>
<div class="container">
  <br/>
  <br/>
  <div class="countries">
    <div class="row">
      <div class="col-md-3 col-12">
      <%= link_to tasting_path(@tasting, :anchor => "africa") do %>  
        <div class="card">
          <%= image_tag ("http://coffeeattendant.com/wp-content/uploads/2018/04/Africa-continent.png"), class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title">Africa</h5>
            <p class="card-text">Flavour Guide</p>
          </div>
        </div>
        <% end %>
      </div>

      <div class="col-md-3 col-12">
      <%= link_to tasting_path(@tasting, :anchor => "camerica") do %>
        <div class="card">
          <%= image_tag ("https://www.coffeeattendant.com/wp-content/uploads/2018/04/central-emrica-1.png"), class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title">Central America</h5>
            <p class="card-text">Flavour Guide</p>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-md-3 col-12">
      <%= link_to tasting_path(@tasting, :anchor => "samerica") do %>
        <div class="card">
          <%= image_tag ("http://coffeeattendant.com/wp-content/uploads/2018/04/South-America-continent.png"), class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title">South America</h5>
            <p class="card-text">Flavour Guide</p>
          </div>
        </div>
        <% end %>
      </div>
      <div class="col-md-3 col-12">
      <%= link_to tasting_path(@tasting, :anchor => "asia") do %>
        <div class="card">
          <%= image_tag ("http://coffeeattendant.com/wp-content/uploads/2018/04/Asia-continent.png"), class: "card-img-top" %>
          <div class="card-body">
            <h5 class="card-title">Asia</h5>
            <p class="card-text">Flavour Guide</p>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="africa-section">
  <a id="africa"><h2>Africa</h2></a>
  <p><strong>Ethiopia:</strong> Ethiopian coffee has distinct fruity flavors such as blueberry and strawberry. Floral notes such as Bergamot, Roses and Jasmine are also often found in a cup. Ethiopian coffees tend to have a high acidity, syrupy mouthfeel and can have a winey quality to it.On filter, the Ethiopian coffees get a tea-like aspect to it as well. Ethiopian coffee is considered among the best in the world.</p>

  <p><strong>Kenya:</strong> Kenyan coffees often have flavors of berries, lemongrass, bergamot, black tea and tomato. The coffee can best be described as vibrant and bright and brings a complex cup to the table. The aftertaste is often described as lemony and grapefruit. On the nose a Kenyan filter coffee might offer a round tomato and black currant aroma. Kenyan coffees are also regarded as high quality coffee.</p>

  <p><strong>Rwanda:</strong> Rwanda coffee will often give floral aromas such as orange blossom and lemon. The flavors consist mostly out of caramelized sugar and dates and a aftertaste of caramel. Fruity flavors such as melon and stone fruits can also often be found in a Rwanda coffee. The acidity is usually crisp and citric.</p>

  <p><strong>Tanzania:</strong> Tanzanian coffee offer a bright and wine like acidity. A medium to full body is often accompanied by notes of sweet berries, fruits and sometimes a hint of cedar wood.</p>
</div>

<div class="camerica-section">
  <a id="camerica"><h2>Central America</h2></a>
  <p><strong>Panama:</strong> Panama is famous for its Geisha coffee and overall quality of coffee in general. Panama coffees often have a Jasmine aroma with flavours of honey and citrus fruits and bergamot. You can also often find a creamy milk chocolate finish in your cup. The Panama coffees are usually round and mild with a medium body and medium acidity.</p>

  <p><strong>Costa Rica:</strong> Good Costa Rican coffees usually have a brown sugar fragrance. The flavors can be divided into apricot, brown sugar and tropical fruits. The aftertaste can bring a dark chocolate to the pallet. The round body is often accompanied with a bright acidity.</p>

  <p><strong>Guatemala:</strong> Guatemalan coffees are known for their mild chocolate/cocoa flavors in the aftertaste. Often you will find a toffee flavor en a nutty aspect in the cup together with tropical fruits as well. The acidity is like that of green apples but on the bright side. Sometimes there is a floral note on the nose. Guatemalan coffees can have a full body often times.</p>

  <p><strong>El Salvador:</strong> Coffees from El Salvador can show aromas and flavors of red fruit and plum. The Acidity is high, the body is medium to full. El Salvador is known for its balanced coffees but they always seem to lack strength in aroma and flavors.</p>

  <p><strong>Nicaragua:</strong> Nicaragua coffees have a mild acidity and medium body smooth body. The flavours are sweet caramel, chocolate and citrus fruits. Often you can find aromas of vanilla and nuts in your cup. The flavors and aromas are rich but balanced.</p>

  <p><strong>Mexico:</strong> Mexican beans are often used in blends because of their excellent blend characteristics. The better Mexican coffees have chocolate flavors and nutty notes as well. They often have a light body and acidity. You may find a dry white wine aspect to the Mexican coffee as well.</p>
</div> 
  
<div class="samerica-section">
  <a id="samerica"><h2>South America</h2></a>
  <p><strong>Colombia:</strong> Colombia is the most famous coffee nation in the world and has many flavors to bring to the cup. Often these coffees have a medium body with aromas of chocolate and cocoa. The flavors, however, will lead you to citrus fruits, sweet tropical fruit and nutty flavors. The Acidity can best be described as bright and citric.</p>

  <p><strong>Brazil:</strong> Brazilian coffees are known for their sweet nutty flavors that are accompanied by a bittersweet chocolate note. Also very common is the hint of toast and low acidity of the Brazilian beans. Because of those agreeable flavours and aromas, Brazilian coffee is often used in blends.</p>

  <p><strong>Peru:</strong> Peruvian coffees can be recognized by their herbal and sweet fruity aromas, together with flavors of plum, sweet citrus fruits such a orange, and herbal notes. The coffee often has a medium to light acidity and medium body. Peruvian coffee is not a famous as their South American brethren but the coffee can be just as great.</p>
</div>
  
<div class="asia-section">
  <a id="asia"><h2>Asia</h2></a>
  <p><strong>Indonesia:</strong> Indonesia is most famous for its Kopi Luwak coffee but they have some other nice coffees as well. Indonesian coffee is easily recognizable by its earthy flavors and aromas that are accompanied by a smokiness and notes of spices. Their full body, rich taste and lasting aftertastes make them favourable with many coffee lovers. Coffees from Papua New Guinea, Thailand and other Asian coffee producing countries are fairly the same when it comes to recognizable flavors and aromas.</p>
</div>