config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :roasts
  resources :items
  resources :stocks
  devise_for :users
  # get 'home/index'
  root 'home#index'
  get 'tasting' => 'home#tasting'
  get "brewing" => 'home#brewing'
  get "hario" => 'home#hario'
  get "stovetop" => 'home#stovetop'
  get "aeropress" => 'home#aeropress'
  get "french_press" => 'home#french_press'
  get "delter_press" => 'home#delter_press'
  get "chemex" => 'home#chemex'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/roast.rb
class Roast < ApplicationRecord
  has_many :comments
end

app/controllers/roasts_controller.rb
class RoastsController < ApplicationController
  before_action :set_roast, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
def index
    @roasts = Roast.all
    @reverse = @roasts.sort.reverse
end

def show
    @comments = @roast.comments.all
    @comment = @roast.comments.build
end

def new
    @roast = Roast.new
end

def edit
end

def create
    @roast = Roast.new(roast_params)

    respond_to do |format|
      if @roast.save
        format.html { redirect_to @roast, notice: 'Roast was successfully created.' }
        format.json { render :show, status: :created, location: @roast }
      else
        format.html { render :new }
        format.json { render json: @roast.errors, status: :unprocessable_entity }
      end
  end
end
def update
    respond_to do |format|
      if @roast.update(roast_params)
        format.html { redirect_to @roast, notice: 'Roast was successfully updated.' }
        format.json { render :show, status: :ok, location: @roast }
      else
        format.html { render :edit }
        format.json { render json: @roast.errors, status: :unprocessable_entity }
      end
    end
end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_roast
      @roast = Roast.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def roast_params
      params.require(:roast).permit(:date, :beans, :s_weight, :f_weight, :air_temp, :roaster, :f_crack_s, :roast_dev, :total_time, :cooling_time, :roast_notes, :end_temp, :end_heat, :drop_temp, :turn_point)
    end

end

app/helpers/roasts_helper.rb
module RoastsHelper
end

app/views/roasts/_card.html.erb
<div class="col-md-1">
      <div class="card" style="width: 18rem;">
        <img src="https://raw.githubusercontent.com/dancorpx/roastlogs/master/app/assets/images/french.png" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title">French Press</h5>
          <p class="card-text">Brew Guide</p>
          <a href="#" class="btn btn-primary">Go somewhere</a>
        </div>
      </div>
</div>

app/views/roasts/_form.html.erb
  <%= simple_form_for(@roast) do |f| %>
    <%= f.error_notification %>
    <div class="row">
      <div class="col-md-3 col-12">
    <%= f.input :date %>
    <%= f.select :beans, ['Brazil', 'China', 'Colombia', 'Costa Rica', 'Ethiopia', 'Ecuador', 'India', 'Honduras', 'Mexico', 'Tanzania', 'Vietnam', 'Uganda', 'Rwanda'], :prompt => "Origin" %>
    <%= f.input :s_weight, :label => "Start Weight:"%>
    <%= f.input :f_weight, :label => "Finish Weight:"%>
    </div>
    <div class="col-md-3 col-12">
    <%= f.input :air_temp %>
    <%= f.input :roaster %>
    <%= f.input :drop_temp, :label => "Charge Temp:" %>
    <%= f.input :turn_point, :label => "Turning Point:" %>
    </div>
    <div class="col-md-3 col-12">
    <%= f.input :f_crack_s, :label => "First crack start:" %>
    <%= f.input :roast_dev, :label => "Dev Time" %>
    <%= f.input :end_temp %>
    <%= f.input :end_heat %>
    </div>
    <div class="col-md-3 col-12">
    <%= f.input :total_time %>
    <%= f.input :roast_notes %>
    </div>
    </div>
<br>
    <%= f.button :submit, class: "btn-primary" %>
    <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
  <% end %>

app/views/roasts/edit.html.erb
<div class="container">
<center><h1>Edit the Roast</h1></center>

<%= render 'form', roast: @roast %>
<br/>
<br/>
<%= link_to 'Back', roasts_path %>

  <br/>
  <br/>

app/views/roasts/index.html.erb
<div class="heading">
    <center><h1>Batch Logs</h1></center>
</div>
<div class="container">
<br>
<br>
<%= link_to 'New Roast', new_roast_path, class: "btn btn-success" %>    
    <br>
    <br>
    <table data-toggle="table" class="table table-striped table-bordered table-sm table-dark" cellspacing="0" width="100%">
    <thead>
        <tr>
        <th class="th-sm">Batch #</th>
        <th class="th-sm" >Date</th>
        <th class="th-sm" data-sortable="true">Bean</th>
        <th class="remove th-sm">Roasting Notes</th>
        <th class="th-sm"> </th>
        </tr>
    </thead>
    <tbody>
    <% @reverse.each do |roast| %>
        <tr>
        <th scope="row"><%= roast.id %></th>
        <td><%= roast.date %></td>
        <td><%= roast.beans %></td>
        <td class="remove"><%= roast.roast_notes %></td>
        <td><%= link_to 'Open', roast_path(roast), class: "btn btn-primary" %></td>
        </tr>
        
        
    <% end %>
    </tbody>
    </table>
<br/>

</div>
<br/>

app/views/roasts/new.html.erb
<div class="container">
<center><h1>New roast time!</h1></center>

<%= render 'form', roast: @roast %>
<br/>
<br/>
<%= link_to 'Back', roasts_path %>

  <br/>
  <br/>

app/views/roasts/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
        <h1>Batch #<%= @roast.id %></h1> 
        <%= link_to 'Edit', edit_roast_path(@roast), class: 'btn btn-warning' %>
        <br/>
        <br/>
        <div class="table-responsive-md">
          <table class="table table-bordered table-dark">
            <thead>
              <th>Batch Date:</th>
              <th>Roaster:</th>
              <th>Beans:</th>
              <th>Start Weight:</th>
              <th>Finish Weight:</th>
              <th>Air Temp:</th>
              <th>Charge Temp:</th>
              <th>Turning Point:</th>
              <th>First crack:</th>
              <th>Dev Time:</th>
              <th>End Temp:</th>
              <th>End Heat:</th>
              <th>Total Time:</th>
              <th>Roasting Notes:</th>
            </thead>
            <tbody>
              <tr>
                <td><%= @roast.date %></td>
                <td><%= @roast.roaster %></td>
                <td><%= @roast.beans %></td>
                <td><%= @roast.s_weight %></td>
                <td><%= @roast.f_weight %></td>
                <td><%= @roast.air_temp %></td>
                <td><%= @roast.drop_temp %></td>
                <td><%= @roast.turn_point %></td>
                <td><%= @roast.f_crack_s %></td>
                <td><%= @roast.roast_dev %></td>
                <td><%= @roast.end_temp %></td>
                <td><%= @roast.end_heat %></td>
                <td><%= @roast.total_time %></td>
                <td><%= @roast.roast_notes %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
  </div>  
  <br/>
  <br/>
  <center><h3>Tasting Comments</h3></center>
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <% @comments.each do |comment| %>
      <div>
        <strong><%= comment.user_name %></strong>
        <br>
        <p><%= comment.body %></p>
        <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
     </div>
    <% end %>
    <%= render partial: 'comments/form', locals: { comment: @comment } %>
    </div>
  </div>
</div>
  <br/>
  <br/>