config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :roasts
  resources :items
  resources :stocks
  devise_for :users
  # get 'home/index'
  root 'home#index'
  get 'tasting' => 'home#tasting'
  get "brewing" => 'home#brewing'
  get "hario" => 'home#hario'
  get "stovetop" => 'home#stovetop'
  get "aeropress" => 'home#aeropress'
  get "french_press" => 'home#french_press'
  get "delter_press" => 'home#delter_press'
  get "chemex" => 'home#chemex'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, required: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
    before_action :set_item, only: [:show, :edit, :update, :destroy]

    def index
        @items = Item.all
        @rev_items = @items.sort.reverse
        @search = params["search"]
        if @search.present?
          @title = @search["title"]
          @rev_items = Item.where("title ILIKE ?", "%#{@title}%")
        end
    end
    
    def new
        @item = Item.new
    end
    
    def edit
    end
    
    def create
        @item = Item.new(item_params)
    
        respond_to do |format|
          if @item.save
            format.html { redirect_to items_path, notice: 'Item was successfully created.' }
            format.json { render :show, status: :created, location: @item }
          else
            format.html { render :new }
            format.json { render json: @item.errors, status: :unprocessable_entity }
          end
      end
    end

    def update
      respond_to do |format|
        if @item.update(item_params)
          format.html { redirect_to items_path, notice: 'item was successfully updated.' }
          format.json { render :show, status: :ok, location: @item }
        else
          format.html { render :edit }
          format.json { render json: @item.errors, status: :unprocessable_entity }
        end
      end
    end


    def destroy
      @item.destroy
      respond_to do |format|
        format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :link, :content, :user_id)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for (@item) do |f| %>
    <%= f.error_notification %>
    <%= f.input :title %>
    <%= f.input :link %>
    <%= f.input :content %>  
    <%= f.input :user_id, :input_html => {:value => current_user.id}, :as => :hidden %>
    <%= f.button :submit, class: "btn-primary" %>
    
<% end %>

app/views/items/edit.html.erb
<div class="container">
    <h1><%= @item.title %></h1>
    <br/>
    <%= render 'form', item: @item %>
    <br/>
    <%= link_to 'Delete', @item, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger"%>
</div>

app/views/items/index.html.erb
<div class="heading">
    <h1>Notes</h1>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <br>
            <h6>Post any useful information you find</h6>
            <br/>
            <div class="form-group">
                <%= simple_form_for :search, url: items_path, method: "GET", html: { class: 'form-inline' } do |f| %>
                    <%= f.input :title, input_html: {value: ""}, label: false %> 
                    <%= f.submit "Search", class: "btn btn-primary", style:"margin-left: 2px;" %>
                <% end %>
            </div>
            <br/>
            <br/>
            <%= link_to 'New Note', new_item_path, class: "btn btn-success", style: "position: relative;
                bottom: 20px; right: 0px;" %>
                
                <% @rev_items.each do |item| %>
                <div class="item">
                    <% if item.user.avatar %>
                        <%= image_tag "#{item.user.avatar}", class: "avatar float-right" %>
                    <% else %>
                        <%= image_tag "https://media1.tenor.com/images/ed2ef9bceac44da18c2eb0711df61106/tenor.gif", class: "avatar float-right" %>
                    <% end %>
                <h2><%= item.title %></h2>
                <%= simple_format item.content %>
                <a href="<%= item.link %>" target="_blank">Go to page</a><br/>
                <p class="text-muted">
                    <small>
                        Posted on <%= item.created_at.to_formatted_s(:long) %>
                    </small>
                </p>               
                <%= link_to 'Edit', edit_item_path(item), class: "btn btn-warning" %><br/>
                </div>
                <% end %>
                
            
            <br/>
            <br/>
                
            <br/>
            <br/>
        </div>
    </div>
</div>

app/views/items/new.html.erb
<div class="container">
<div class="row">
  <div class="col-md-6 offset-md-3">
  <center><h1>New note!</h1></center>

  <%= render 'form', roast: @item %>
  <br/>
  <br/>
  <%= link_to 'Back', items_path %>

  <br/>
  <br/>
  </div>
</div>

app/views/items/show.html.erb
<div class="heading">
    <h1><%= @item.title %></h1>
</div>
<div class="container">
<br>
<a class="text-danger" href="<%= @item.link %>" target="_blank"><%= @item.link %></a>


<p><%= @item.content %></p>

<br><br><br>

<%= link_to 'Back to Notes', items_path, class: "btn btn-primary" %><br/>